version: 2
updates:
  - package-ecosystem: github-actions
    directory: .
    schedule:
      interval: daily
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: .
    schedule:
      interval: daily
