site_name: recipes
site_url: https://thms317.github.io/recipes/

nav:
  - Introduction: index.md
  - Recipes:
      - Banana-Peanut Butter Granola with Whole Nuts: recipes/granola.md
      - Dutch Vegetarian Chili: recipes/dutch_veggie_chili.md
      - Port-Caramelized Onions: recipes/port_caramelized_onions.md
  - Recipe Database: recipe_database.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top

plugins:
  - search
  - recipes:
      recipes_dir: recipes
      images_dir: recipes/images

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - css/custom.css

repo_url: https://github.com/thms317/recipes
edit_uri: edit/main/docs/
