site_name: recipes
site_url: https://thms317.github.io/recipes/

nav:
  - Introduction: index.md
  - Recipes:
      - Banana-Peanut Butter Granola: recipes/granola.md
      - Vegetarische Chili: recipes/chili_vega.md
      - Port-Caramelized Onions: recipes/port_caramelized_onions.md
      - Boterkoek: recipes/boterkoek.md
      - Appeltaart: recipes/appeltaart.md
      - Zoete Aardappelsoep: recipes/zoete_aardappelsoep.md
  - Recipe Database: recipe_database.md
  - LLM Instructions: llm_instructions.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.expand
    - navigation.top

plugins:
  - search
  - recipes:
      recipes_dir: recipes
      images_dir: recipes/images

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - css/custom.css

repo_url: https://github.com/thms317/recipes
edit_uri: edit/main/docs/
